// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPbBAlLIGkIGcdF5NRC_v7LjxqajcsOzc',
    appId: '1:380003583452:web:e532f5ee09102b0ef1fb19',
    messagingSenderId: '380003583452',
    projectId: 'natalia-siddharta',
    authDomain: 'natalia-siddharta.firebaseapp.com',
    storageBucket: 'natalia-siddharta.firebasestorage.app',
    measurementId: 'G-DY7YSFWSB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm74dI-HsAtOHhv5BVCKRKFIbqO2s_-Yk',
    appId: '1:380003583452:android:c2b8d2b18dfbcb8ff1fb19',
    messagingSenderId: '380003583452',
    projectId: 'natalia-siddharta',
    storageBucket: 'natalia-siddharta.firebasestorage.app',
  );
}
