// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTSFvOWUQFRu9vFOjlfWKJwidd2-ntqKA',
    appId: '1:146165245118:web:6205602be7983af6d4aaef',
    messagingSenderId: '146165245118',
    projectId: 'notes-41456',
    authDomain: 'notes-41456.firebaseapp.com',
    storageBucket: 'notes-41456.firebasestorage.app',
    measurementId: 'G-YYTP3Q20X6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwgrVqEUzWBc7Bv_iBGMZ7abN8SOiojIo',
    appId: '1:146165245118:android:1737453404667794d4aaef',
    messagingSenderId: '146165245118',
    projectId: 'notes-41456',
    storageBucket: 'notes-41456.firebasestorage.app',
  );
}
